### ISSUE TITLE
Got an error 0xe00d when executing QuoteGeneration Sample

### ISSUE THREAD

**Issue by RMheng** [intel/SGXDataCenterAttestationPrimitives#63] opened 2020-01-02 08:04 UTC
Hi,
I installed dcap driver and /dev/sgx appeared. But when executing samplecode, I got error:

This step is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!
[load_pce ../pce_wrapper.cpp:123] Error, call sgx_create_enclave for PCE fail [load_pce], SGXError:0001.
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe00d

I'm confused that whether I didn't install dcap driver correctly? But I didn't got error when I installed. And I referred to the procedure https://github.com/bitsyizhan/sgx/blob/master/Intel_SGX_DCAP_Linux_SW_Installation_Guide.pdf.

Thanks for your time!!!

**Comment by hyjiang** [comment] 2020-01-22 07:12
You need to follow installation guide to install & configure PCCS. 
Alternatively, you can remove the default QPL package, but the generated quote cannot be verified by QvE.

**Comment by ccolin318** [comment] 2020-04-06 19:57
Hi, 
I'm getting a similar error when I run the QuoteGeneration sample code. I'm running in hardware mode with SGX2 + FLC.

Here's the output:
This step is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe011

Any advice on resolving this error or what the cause may be?
Thanks!

**Comment by hyjiang** [comment] 2020-04-06 23:56
Pls make sure you have configured PCCS correctly, you can follow PCCS README.
Also, **In test env**, you need to change to "USE_SECURE_CERT=FALSE" in file /etc/sgx_default_qcnl.conf.

**Comment by ccolin318** [comment] 2020-04-08 11:43
Thank you for your help, I have it working now.

**Closed** 2022-06-30 01:29 UTC
